### ISSUE TITLE
[aurora] Add support for RDS Aurora

### ISSUE THREAD

**Issue by pflorek** [cdklabs/cdk-monitoring-constructs#217]
### Feature scope

AWS/RDS

### Describe your suggested feature

Hey together,

I would like to monitor Aurora. The CDK implementation, underlying CFN resource and metrics/namespace is almost same to RDS (sure some won't apply).

Currently, I'm just type casting `IServerlessCluster`, which feels brittle: `cluster as unknown as rds.IDatabaseCluster`

<img width="1350" alt="Bildschirmfoto 2022-08-15 um 17 26 18" src="https://user-images.githubusercontent.com/13916107/184664982-ef58e7e2-e9df-47f2-9195-9d9bb5f47f93.png">

**Comment by voho** [comment]
Thanks for the suggestion. Will start with the implementation soon. Any aurora-specific metrics you would like not to be missed?

**Comment by zqumei0** [comment]
I figured I would take a stab at this since I didn't see anything yet. Happy to get some feedback on implementation of this. Most of the metrics are the same but ServerlessCluster had serverless specific metrics, so I used the same metrics factory as RDS but a separate monitor to pull different metrics. I only added `Serverless Database Capacity` cluster metric and a corresponding alarm. Need to look into more metrics that are good to have. Let me know if either of you have any thoughts!
