### ISSUE TITLE
Better Documentation Needed

### ISSUE THREAD

**Issue by shellscape** [cdklabs/cdk-monitoring-constructs#343]
There are some phenomenal constructs in this package, very well done. However, gleaning how to use the constructs in the package is currently extremely painful and requires source diving the tests.

For example, there's no mention of `MonitoringScope` in the README nor in any page within the repo or constructs hub in documentation that discusses usage. It's only when you start to try and use the constructs are we alerted that `MonitoringScope` is required. Not only that, but it's abstract and requires inheritance. 

There's also no mention that it's abstract on `MonitoringScope`s constrcut hub docs https://constructs.dev/packages/cdk-monitoring-constructs/v/3.0.4/api/MonitoringScope?lang=typescript

A recipes or examples directory would go a long way to resolving the documentation shortage here. But any amount of documentation above what currently exists would be welcome. I'd highly encourage the maintainers to take a page from the AWS CDK docs and provide an "Overview" page that lists example usage, starting with something complete that include source code for all requirements to using a construct.

**Comment by cayman-amzn** [comment]
> For example, there's no mention of MonitoringScope in the README nor in any page within the repo or constructs hub in documentation that discusses usage.

I see it elaborated on here, with an example:
- https://constructs.dev/packages/cdk-monitoring-constructs/v/3.0.4?lang=typescript#monitoring-scopes
- https://github.com/cdklabs/cdk-monitoring-constructs#monitoring-scopes

FWIW, the `.monitorScope` API is still [marked with `@experimental`](https://github.com/cdklabs/cdk-monitoring-constructs/blob/4217bb92c640dfedeb7270763257a9f83f907c56/lib/facade/MonitoringFacade.ts#L693)

----

While I do think that some examples of the more complex APIs could be useful, providing examples for every facet may eventually turn into a lost cause since we're talking about providing examples for every component of the AWS-CDK. Although, it would be cool to see some sort of coverage system... ie showing the which lines in the AWS-CDK package(s) are covered/monitored by this repo. 

And of course you're always welcome to [contribute](https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/CONTRIBUTING.md) to this community-maintained project.

**Comment by shellscape** [comment]
Thanks for getting back to me so quickly. In this case, casing matters. `MonitoringScope` (the construct) is not the same as `.monitorScope` the convenience method. Unfortunately `MonitoringScope` doesn't appear on either of the pages you linked.

AWS CDK does a really good job of minimum usage examples for most L2 constructs. I run into one with very light usage examples now and then, but it's rare. I agree a baseline goal would be nice.
