### ISSUE TITLE
[Infra] Improve eslint/prettier setup

### ISSUE THREAD

**Issue by voho** [cdklabs/cdk-monitoring-constructs#99]
### Feature scope

build

### Describe your suggested feature

I think our Projen setup is inconsistent in how it applies eslint/prettier rules. Seems to me that there are two conflicting definitions, or something like that - for example, the lines are wrapped eagerly, which is not what I would expect. I think we have to find a way to specify the rules on single place and then make all the tools use the same config.

Found this example:

https://github.com/p6m7g8/awesome-projen/blob/main/.eslintrc.json

**Comment by ayush987goyal** [comment]
The formatting might have been happening eagerly because we have `source.fixAll.eslint` to `true` on save in the VSCode settings for the project: https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/.vscode/settings.jso.

Is this not what is expected? What are the inconsistencies that you have observed?

**Comment by voho** [comment]
I think the line wrapping is very tight, although we did not observe the same in the internal package. I am actually not sure if we use eslint or prettier for formatting, and where the SSOT is, since we have config for both :).

**Comment by rahul0705** [comment]
One addition, would be to improve the `.gitignore` as when trying to build all the resultant files in the test directory were not being ignored. Maybe using a [gitignore generator](https://www.toptal.com/developers/gitignore) would be helpful?

**Comment by echeung-amzn** [comment]
For reference, the internal ESLint configuration is currently set to:

```js
module.exports = {
    env: {
        es2021: true
    },
    extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended", "plugin:prettier/recommended"],
    parser: "@typescript-eslint/parser",
    parserOptions: {
        ecmaVersion: 2018,
        sourceType: "module"
    },
    plugins: ["@typescript-eslint", "unused-imports"],
    rules: {
        "unused-imports/no-unused-imports": "error",
        "no-case-declarations": "off",

        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/no-unused-vars": ["error", {argsIgnorePattern: "^_"}],

        "prettier/prettier": [
            "error",
            {
                arrowParens: "always",
                bracketSpacing: false,
                printWidth: 140,
                semi: true,
                tabWidth: 4,
                trailingComma: "all",
            }
        ]
    }
};
```

But we opted to stick with projen's default configs when setting up this repo to avoid some weird mismatches/churn.

There probably isn't much benefit to necessarily matching 1-1 since the codebases are fully separate anyway, but the line wrapping would likely be addressed by setting Prettier's `printWidth` setting.

**Comment by echeung-amzn** [comment]
I'll tackle this at some point next week.

**Comment by echeung-amzn** [comment]
The defaults are generally fine. I enforced trailing commas in https://github.com/cdklabs/cdk-monitoring-constructs/commit/cf26388df7a09666590668a6430128ba9b1b5bb7
